Testing market interaction
TlStephen2011/fixme pull request #6
Opened 2019-09-09 13:39 UTC by TlStephen2011

Interaction between broker and market is working, broker receiving broadcasts from market via router, need to test random disconnects among clients to see if it still works. Market needs to add executed or rejected logic.

2019-09-09 16:13 UTC, diVid3 commented on fixme-parent/fixme-broker/src/main/java/za/co/wethinkcode/broker/Broker.java
> +    private Scanner fromRouter;
This was added as processResponse was creating its own new scanner, thus dropping the state of the scanner created in the constructor, which will contain messages if the broker connects first and then the market.

2019-09-09 16:59 UTC, diVid3 requested changes
There seems to be a slight issue when closing the router unexpectedly, causing an input loop at broker CLI.

2019-09-09 18:14 UTC, TlStephen2011 commented
> There seems to be a slight issue when closing the router unexpectedly, causing an input loop at broker CLI.

2019-09-09 18:37 UTC, TlStephen2011 commented
hotfix added

2019-09-09 18:38 UTC, TlStephen2011 reviewed
Will the line ever equal "", besides when connection to router is broken?

2019-09-09 19:05 UTC, diVid3 commented
> Will the line ever equal "", besides when connection to router is broken?

No not that I know of.

2019-09-09 19:07 UTC, diVid3 approved these changes
Looking good. Approved 👍

2019-09-10 07:42 UTC, mmbatha approved these changes

2019-09-10 09:18 UTC, merged